trigger:
- main

pr:
- main

strategy:
  matrix:
    Windows:
      vmImage: windows-latest
    Ubuntu:
      vmImage: ubuntu-latest

pool:
  vmImage: $(vmImage)

steps:
- task: PowerShell@2
  displayName: Resolve dependencies and init
  inputs:
    pwsh: true
    targetType: inline
    script: |
      ./Build/build.ps1 -ResolveDependency -TaskList init

- task: PowerShell@2
  displayName: Stage, analyze, and test
  inputs:
    pwsh: true
    targetType: inline
    script: |
      ./Build/build.ps1 -TaskList stage
      ./Build/build.ps1 -TaskList analyze
      ./Build/build.ps1 -TaskList test
